name: Lint PR Title

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint PR Title
        uses: benhodgson87/conventional-pull-request-action@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitlintRulesPath: './commitlint.rules.js'
          enforcedScopeTypes: 'feat|fix|chore'
          scopeRegex: '\b(FOO|BAR|BAZ)\b-[0-9]+'
